kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: Mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/org-twinkal/Terraform-AKS.git
    targetRevision: main
    path: chatapp-gitops/mongodb

  destination:
    server: https://twinkalaks-3kan2abl.hcp.eastus.azmk8s.io:443
    namespace: chatapp
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true